// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var canvas = window.document.createElement("canvas");
	canvas.width = 400;
	canvas.height = 400;
	window.document.body.appendChild(canvas);
	var ctx = canvas.getContext("2d");
	var x = 50;
	var y = 50;
	var speed = 3;
	var loop = null;
	loop = function(time) {
		x += speed;
		if(x > 400) {
			x = 0;
		}
		ctx.fillStyle = "blue";
		ctx.fillRect(0,0,400,400);
		ctx.fillStyle = "red";
		ctx.fillRect(x,y,50,50);
		window.requestAnimationFrame(loop);
	};
	window.requestAnimationFrame(loop);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
