// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Teller = function(getal) {
	this.getal1 = 4;
	this.getal = getal;
};
Teller.prototype = {
	countUp: function() {
		console.log("src/Main.hx:11:",this.getal1 + this.getal);
	}
};
var Main = function() { };
Main.main = function() {
	new Teller(20).countUp();
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
