// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Dog = function(name,age) {
	this.name = name;
	this.age = age;
};
Dog.prototype = {
	bark: function() {
		console.log("src/Main.hx:11:","Woof i am " + this.name + " and i am " + this.age);
	}
	,rename: function(newName) {
		this.name = newName;
	}
	,birthdag: function() {
		this.age += 1;
	}
};
var Main = function() { };
Main.main = function() {
	var dog1 = new Dog("Fie",14);
	var dog2 = new Dog("Max",8);
	var dog3 = new Dog("Bobby",5);
	dog1.birthdag();
	dog1.bark();
	dog3.bark();
	dog2.rename("Rex");
	dog2.bark();
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
